apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  ports:
  - port: {{ .Values.port }}
    targetPort: {{ .Values.port }}
  type: LoadBalancer
  selector:
    app: guestbook-ui
